# -*- coding: utf-8 -*-
"""iris

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVmY5rl8ODULKT9LB4MPSkjD39yAYPdk
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_style('whitegrid')

df=sns.load_dataset('iris')

print("Dataset Preview:")
print(df.head())
print("\nDataset Shape:",df.shape)

print("===BASIC INFORMATION===")
print("\ncolumn names and datatypes:")
print(df.info())
print("\n Summary Statistics:")
print(df.describe())
print("\nCategorial Column Unique Values:")
print("Species:",df['species'].unique())

print("===Missing Values===")
missing=df.isnull().sum()
print("Missing Values per column")
print(missing)
if missing.sum()==0:
  print("Great! No missing values found.")
else:
  plt.figure(figsize=(8,4))
  sns.heatmap(df.isnull(),cbar=False,cmap='viridis')
  plt.title('Missing Values Heatmap')
  plt.show()

print("\n===DUPLICATES===")
print("Duplicates before cleaning:",df.duplicated().sum())
if df.duplicated().sum()>0:
  print("\nDuplicate rows:")
  print(df[df.duplicated()])
  df=df.drop_duplicates()
  print("Duplicates after cleaning:",df.duplicated().sum())

print("\n===UNIVARIATE ANALYSIS===")
num_cols=['sepal_length','sepal_width','petal_length','petal_width']
fig,axes=plt.subplots(2,2,figsize=(12,8))
axes=axes.flatten()
for i ,col in enumerate(num_cols):
  sns.histplot(data=df,x=col,kde=True,ax=axes[i],bins=20)
  axes[i].set_title(f'Distribution of{col.replace("_"," ").title()}')
  axes[i].set_xlabel(col.replace("_"," ").title())
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
species_counts=df['species'].value_counts()
colors=['lightcoral','lightblue','lightgreen']
species_counts.plot(kind='bar',color=colors,edgecolor='black')
plt.title('Species Distribution')
plt.xlabel('Species')
plt.ylabel('Count')
plt.xticks(rotation=0)
plt.show()
print("\nSpecies distribution percentage:")
print(df['species'].value_counts(normalize=True).round(3)*100)

print("\n===BIVARIATE ANALYSIS===")
plt.figure(figsize=(10,6))
sns.scatterplot(data=df,x='sepal_length',y='sepal_width',hue='species',style='species',s=100,alpha=0.8)
plt.title('Sepal Length vs Sepal Width by Species')
plt.xlabel('Sepal Length(cm)')
plt.ylabel('Sepal Width(cm)')
plt.legend(title='Species')
plt.show()
fig,axes=plt.subplots(2,2,figsize=(14,10))
axes=axes.flatten()
for i,col in enumerate(num_cols):
  sns.boxplot(data=df,x='species',y=col,ax=axes[i],palette='Set2')
  axes[i].set_title(f'{col.replace("_"," ").title()}by species')
  axes[i].set_xlabel('species')
  axes[i].set_ylabel(col.replace("_"," ").title())
plt.tight_layout()
plt.show()

print("\n===OUTLIER DETECTION===")
plt.figure(figsize=(12,6))
df[num_cols].boxplot()
plt.title('Boxplot for Outlier Detection')
plt.ylabel('Measurement(cm)')
plt.xticks(rotation=45)
plt.show()
print("\nOutlier analysis using IQR method:")
for col in num_cols:
  Q1=df[col].quantile(0.25)
  Q3=df[col].quantile(0.75)
  IQR=Q3-Q1
  lower_bound=Q1-1.5*IQR
  upper_bound=Q3+1.5*IQR
  outliers=df[(df[col]<lower_bound)|(df[col]>upper_bound)]
  print(f"{col:15s}:{len(outliers):2d}outlier"f"({len(outliers)/len(df)*100:.1f}%)")
  if len(outliers)>0:
    print(f"Outlier Values:{outliers[col].values}")

print("\nCORRELATION ANALYSIS===")
corr_matrix=df[num_cols].corr()
plt.figure(figsize=(8,6))
sns.heatmap(corr_matrix,annot=True,cmap='coolwarm',center=0,fmt='.2f',square=True,linewidths=1)
plt.title('Correlation Heatmap of Iris Measurements')
plt.show()
print("\nCorrelation Matrix:")
print(corr_matrix.round(3))

print("\n===PAIRWISE RELATIONSHIP===")
pairplot=sns.pairplot(df,hue='species',palette='Set2',diag_kind='kde',height=2.5)
pairplot.fig.suptitle('Pairwise Relationship in Iris Dataset',y=1.02)
plt.show()
sns.pairplot(df,hue='species',diag_kind='hist',palette='husl')
plt.suptitle('Pairwise Relationship with Histogram',y=1.02)
plt.show()

print("\n===CATEGORIAL INSIGHTS===")
print("\n1.Species Statistics:")
for species in df['species'].unique():
  print(f"\n---{species.upper()}---")
  species_data=df[df['species']==species]
  print(f"count:{len(species_data)}samples({len(species_data)/len(df)*100:.1f}%)")

  for col in num_cols:
    print(f"{col:15s}:Mean={species_data[col].mean():.2f}cm,"f"Std={species_data[col].std():.2f}cm")
print("\n2.Statistical Summary by species:")
summary_by_species=df.groupby('species')[num_cols].agg(['mean','std','min','max'])
print(summary_by_species.round(2))

fig,axes=plt.subplots(2,2,figsize=(14,10))
axes=axes.flatten()

for i ,col in enumerate(num_cols):
  species_means=df.groupby('species')[col].mean()
  species_stds=df.groupby('species')[col].std()

  bars=axes[i].bar(species_means.index,species_means.values,color=['lightcoral','lightblue','lightgreen'],edgecolor='black',alpha=0.7)

  axes[i].errorbar(species_means.index,species_means.values,yerr=species_stds.values,fmt='none',color='black',capsize=5)

  axes[i].set_title(f'Average{col.replace("_"," ").title()}by species')
  axes[i].set_ylabel(f'{col.replace("_"," ").title()}(cm)')

  for bar,mean_val in zip(bars,species_means.values):
    height=bar.get_height()
    axes[i].text(bar.get_x()+bar.get_width()/2.,height+0.02,f'{mean_val:.2f}',ha='center',va='bottom')

plt.tight_layout()
plt.show()



