# -*- coding: utf-8 -*-
"""EDA DATA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Qw-IiHJBRoLzJmB-VmAbYJBqU9XIr4U
"""

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/student - Sheet1.csv")
df.info()
df.describe()
df['Marks'].hist()
df.plot.scatter(x='Study_Hours',y='Marks')
df.corr()
df.boxplot(column='Marks')